leftnav:
- identifier: 7dc4baa4-4dc7-ceea-abce-9481f263598f
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 19c6098c-89fb-fdf8-433f-44041637aea0
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: dd9ffc10-50bf-d6cd-6e01-44621a70ba19
  name: Projects
  pageRef: /pages/projects/
  weight: 30
- identifier: a83643c7-dfac-f72f-ed43-f0dfe886398d
  name: Tools
  pageRef: /pages/tools
  weight: 40
- identifier: ab137c9e-6878-e1e9-5139-22cf2c4055f0
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
